### ISSUE TITLE
formatting of colon is shifted to the left in a math assignment

### ISSUE THREAD

**Issue by sanderhahn** [denoland/deno-gfm#125]
The colon in shifted to the left, see screenshot:

![Screenshot 2024-07-27 at 15 08 51](https://github.com/user-attachments/assets/4738445e-05ff-4bad-9a4c-6ae69960e374)

```md
$x:=x$
```

On github:

$x:=x$

Also I needed to add this to the css to hide the unformatted formulas:

```css
    *[aria-hidden="true"] {
      display: none;
    }
```
